
export const AUTH_USERS = [
    { establishment: "ESCUELA SAN MIGUEL", key: "Sanmi10778" },
    { establishment: "LICEO BICENTENARIO HERMANOS SOTOMAYOR BAEZA", key: "71293130" },
    { establishment: "POLITECNICO", key: "MACARENA123" },
    { establishment: "ESCUELA IGNACIO SERRANO MONTANER", key: "arbra121" },
    { establishment: "LICEO GABRIELA MISTRAL DE MELIPILLA", key: "Gab2022h" },
    { establishment: "COLEGIO HUILCO ALTO", key: "71293114" },
    { establishment: "COLEGIO MONS. JAIME LARRAIN BUNSTER", key: "larrain2024" },
    { establishment: "ESCUELA SAN JOSE DE LA VILLA", key: "10786454" },
    { establishment: "ESCUELA GRAL. CAROL URZUA", key: "78910carol" },
    { establishment: "ESCUELA REPUBLICA DEL BRASIL", key: "RBRASIL24" },
    { establishment: "COLEGIO POMAIRE", key: "eriamop2" },
    { establishment: "LICEO POLIV. EL BOLLENAR", key: "Director2022*" },
    { establishment: "ESCUELA SANTA ROSA ESMERALDA", key: "Esanta10" },
    { establishment: "ESCUELA CLAUDIO ARRAU", key: "Eca107956" },
    { establishment: "ESCUELA PATRICIO LARRAIN GANDARILLAS", key: "santaelisa10" },
    { establishment: "ESCUELA PEDRO MARIN ALEMANY", key: "pm71293113" },
    { establishment: "ESCUELA BASICA CARMEN BAJO", key: "Cbajo26" },
    { establishment: "ESCUELA RAMON NOGUERA PRIETO", key: "Clou2025" },
    { establishment: "ESCUELA PUANGUE", key: "71293199" },
    { establishment: "ESCUELA LIDIA MATTE HURTADO", key: "71293118" },
    { establishment: "ESCUELA JOSE CAMARENA ESCRIVA", key: "Wilson12" },
    { establishment: "ESCUELA HUECHUN", key: "colegio1965" },
    { establishment: "ESCUELA RAQUEL FERNANDEZ DE MORANDE", key: "Rf71293187" },
    { establishment: "ESCUELA PADRE ALBERTO HURTADO", key: "71293186" },
    { establishment: "ESCUELA BASICA EL PABELLON", key: "Larrain10827" },
    { establishment: "LICEO LOS JAZMINES", key: "Jazm1nL1c30" },
    { establishment: "ADMINISTRADOR", key: "10031981" },
    { establishment: "Docente8327", key: "&U#Bo7wf5hmO" },
    { establishment: "Docente7963", key: "ro8yIWOxXDu9" },
    { establishment: "Docente1126", key: "K!1*m5dV3GsA" },
    { establishment: "Docente7769", key: "wdz5LxqYe8x%" },
    { establishment: "Docente3395", key: "WPoR$zLABNLg" },
    { establishment: "Docente3973", key: "rMA&WRA5AAQ@" },
    { establishment: "Docente3727", key: "06te3lSHbBKi" },
    { establishment: "Docente9628", key: "8p%7vQD8H8Gt" },
    { establishment: "Docente9640", key: "t1@cH77Laf*J" },
    { establishment: "Docente5052", key: "2E*Ga7rRcW9Y" },
    { establishment: "Docente4857", key: "o$kj%UXmwL02" },
    { establishment: "Docente5929", key: "1IViUGx^wdZx" },
    { establishment: "Docente8042", key: "0lOB&0dGyHCn" },
    { establishment: "Docente3045", key: "hnnbKIJPWjFl" },
    { establishment: "Docente2842", key: "L3dzEKEQNGDs" },
    { establishment: "Docente1415", key: "FIq7qZht7lKJ" },
    { establishment: "Docente3676", key: "7ozEmUF#lM0E" },
    { establishment: "Docente3228", key: "!mDFreEks0lM" },
    { establishment: "Docente6647", key: "GWhEdb*&%I&j" },
    { establishment: "Docente4157", key: "0GiFmMtdmsOk" },
    { establishment: "Docente5590", key: "sdwOL#1rOjUm" },
    { establishment: "Docente5576", key: "!Bo#fwHAGOiu" },
    { establishment: "Docente3184", key: "@ri5ePs!wV8K" },
    { establishment: "Docente8866", key: "Xt2fOl!o%QVM" },
    { establishment: "Docente9446", key: "dQGtRIa4e^6T" },
    { establishment: "Docente4178", key: "CQgaAUBWZoe9" },
    { establishment: "Docente2278", key: "Ic*19v*SgCXz" },
    { establishment: "Docente3606", key: "XW%h6KzyQ0on" },
    { establishment: "Docente5155", key: "L9sPj5&3Zy!h" },
    { establishment: "Docente1561", key: "wEHI4eUCB9o&" }
];
