
export const AUTH_USERS = [
    { establishment: "ESCUELA SAN MIGUEL", key: "Sanmi10778" },
    { establishment: "LICEO BICENTENARIO HERMANOS SOTOMAYOR BAEZA", key: "71293130" },
    { establishment: "POLITECNICO", key: "MACARENA123" },
    { establishment: "ESCUELA IGNACIO SERRANO MONTANER", key: "arbra121" },
    { establishment: "LICEO GABRIELA MISTRAL DE MELIPILLA", key: "Gab2022h" },
    { establishment: "COLEGIO HUILCO ALTO", key: "71293114" },
    { establishment: "COLEGIO MONS. JAIME LARRAIN BUNSTER", key: "larrain2024" },
    { establishment: "ESCUELA SAN JOSE DE LA VILLA", key: "10786454" },
    { establishment: "ESCUELA GRAL. CAROL URZUA", key: "78910carol" },
    { establishment: "ESCUELA REPUBLICA DEL BRASIL", key: "RBRASIL24" },
    { establishment: "COLEGIO POMAIRE", key: "eriamop2" },
    { establishment: "LICEO POLIV. EL BOLLENAR", key: "Director2022*" },
    { establishment: "ESCUELA SANTA ROSA ESMERALDA", key: "Esanta10" },
    { establishment: "ESCUELA CLAUDIO ARRAU", key: "Eca107956" },
    { establishment: "ESCUELA PATRICIO LARRAIN GANDARILLAS", key: "santaelisa10" },
    { establishment: "ESCUELA PEDRO MARIN ALEMANY", key: "pm71293113" },
    { establishment: "ESCUELA BASICA CARMEN BAJO", key: "Cbajo26" },
    { establishment: "ESCUELA RAMON NOGUERA PRIETO", key: "Clou2025" },
    { establishment: "ESCUELA PUANGUE", key: "71293199" },
    { establishment: "ESCUELA LIDIA MATTE HURTADO", key: "71293118" },
    { establishment: "ESCUELA JOSE CAMARENA ESCRIVA", key: "Wilson12" },
    { establishment: "ESCUELA HUECHUN", key: "colegio1965" },
    { establishment: "ESCUELA RAQUEL FERNANDEZ DE MORANDE", key: "Rf71293187" },
    { establishment: "ESCUELA PADRE ALBERTO HURTADO", key: "71293186" },
    { establishment: "ESCUELA BASICA EL PABELLON", key: "Larrain10827" },
    { establishment: "LICEO LOS JAZMINES", key: "Jazm1nL1c30" },
    { establishment: "ADMINISTRADOR", key: "10031981" }
];
